// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameDefinition,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  gameId: __t.u64().name("game_id"),
  version: __t.u32(),
  draftId: __t.u64().name("draft_id"),
  draftRevision: __t.u32().name("draft_revision"),
  get definition() {
    return GameDefinition;
  },
  publishedAt: __t.timestamp().name("published_at"),
});
