// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.1 (commit 3d7607082ab47257adeb7c25164536511237f2b5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddCoinReducer from "./add_coin_reducer";
import AddDiceReducer from "./add_dice_reducer";
import AdvanceTurnPhaseReducer from "./advance_turn_phase_reducer";
import ConcedeMatchReducer from "./concede_match_reducer";
import CreateCardReducer from "./create_card_reducer";
import CreateCardFormatReducer from "./create_card_format_reducer";
import CreateCardInteractionReducer from "./create_card_interaction_reducer";
import CreateCardTriggerReducer from "./create_card_trigger_reducer";
import CreateConstraintReducer from "./create_constraint_reducer";
import CreateDeckRulesReducer from "./create_deck_rules_reducer";
import CreateExampleDraftReducer from "./create_example_draft_reducer";
import CreateFieldReducer from "./create_field_reducer";
import CreateGameDraftReducer from "./create_game_draft_reducer";
import CreateHandSizeReducer from "./create_hand_size_reducer";
import CreateLifeReducer from "./create_life_reducer";
import CreateParticipantLimitsReducer from "./create_participant_limits_reducer";
import CreateRoomReducer from "./create_room_reducer";
import CreateSetupReducer from "./create_setup_reducer";
import CreateSpaceReducer from "./create_space_reducer";
import CreateStarterDeckReducer from "./create_starter_deck_reducer";
import CreateSubPhasesReducer from "./create_sub_phases_reducer";
import CreateTurnPhasesReducer from "./create_turn_phases_reducer";
import CreateWinConditionReducer from "./create_win_condition_reducer";
import DeleteDeckReducer from "./delete_deck_reducer";
import DeleteDecksReducer from "./delete_decks_reducer";
import DeleteGamesReducer from "./delete_games_reducer";
import JoinRoomReducer from "./join_room_reducer";
import LeaveRoomReducer from "./leave_room_reducer";
import PassReactionReducer from "./pass_reaction_reducer";
import PublishGameReducer from "./publish_game_reducer";
import ReactToActionReducer from "./react_to_action_reducer";
import SaveDeckReducer from "./save_deck_reducer";
import SelectDeckReducer from "./select_deck_reducer";
import SetNameReducer from "./set_name_reducer";
import SetReadyReducer from "./set_ready_reducer";
import StartMatchReducer from "./start_match_reducer";
import TakeActionReducer from "./take_action_reducer";
import UpdateDesignerDraftReducer from "./update_designer_draft_reducer";
import UpdateGameDraftReducer from "./update_game_draft_reducer";
import UpdateResourceDesignerDraftReducer from "./update_resource_designer_draft_reducer";
import UpdateSpecialDesignerDraftReducer from "./update_special_designer_draft_reducer";
import ValidateGameDraftReducer from "./validate_game_draft_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import DeletedGameRow from "./deleted_game_table";
import GameVersionRow from "./game_version_table";
import MatchHistoryRow from "./match_history_table";
import MatchPlayersRow from "./match_players_table";
import MyDecksRow from "./my_decks_table";
import MyDraftResourceRulesRow from "./my_draft_resource_rules_table";
import MyDraftRulesRow from "./my_draft_rules_table";
import MyDraftSpecialRulesRow from "./my_draft_special_rules_table";
import MyDraftsRow from "./my_drafts_table";
import MyMatchResourceBalancesRow from "./my_match_resource_balances_table";
import MyMatchesRow from "./my_matches_table";
import MyMembershipsRow from "./my_memberships_table";
import MyReactionWindowsRow from "./my_reaction_windows_table";
import PublishedGameRow from "./published_game_table";
import RoomRow from "./room_table";
import RoomParticipantsRow from "./room_participants_table";
import UserRow from "./user_table";
import VersionResourceRulesRow from "./version_resource_rules_table";
import VersionRulesRow from "./version_rules_table";
import VersionSpecialRulesRow from "./version_special_rules_table";
import VisibleMatchCardsRow from "./visible_match_cards_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  deletedGame: __table({
    name: 'deleted_game',
    indexes: [
      { accessor: 'gameId', name: 'deleted_game_game_id_idx_btree', algorithm: 'btree', columns: [
        'gameId',
      ] },
    ],
    constraints: [
      { name: 'deleted_game_game_id_key', constraint: 'unique', columns: ['gameId'] },
    ],
  }, DeletedGameRow),
  gameVersion: __table({
    name: 'game_version',
    indexes: [
      { accessor: 'gameId', name: 'game_version_game_id_idx_btree', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { accessor: 'id', name: 'game_version_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_version_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameVersionRow),
  publishedGame: __table({
    name: 'published_game',
    indexes: [
      { accessor: 'id', name: 'published_game_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'published_game_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PublishedGameRow),
  room: __table({
    name: 'room',
    indexes: [
      { accessor: 'host', name: 'room_host_idx_btree', algorithm: 'btree', columns: [
        'host',
      ] },
      { accessor: 'id', name: 'room_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'room_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RoomRow),
  user: __table({
    name: 'user',
    indexes: [
      { accessor: 'identity', name: 'user_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
  versionResourceRules: __table({
    name: 'version_resource_rules',
    indexes: [
      { accessor: 'versionId', name: 'version_resource_rules_version_id_idx_btree', algorithm: 'btree', columns: [
        'versionId',
      ] },
    ],
    constraints: [
      { name: 'version_resource_rules_version_id_key', constraint: 'unique', columns: ['versionId'] },
    ],
  }, VersionResourceRulesRow),
  versionRules: __table({
    name: 'version_rules',
    indexes: [
      { accessor: 'versionId', name: 'version_rules_version_id_idx_btree', algorithm: 'btree', columns: [
        'versionId',
      ] },
    ],
    constraints: [
      { name: 'version_rules_version_id_key', constraint: 'unique', columns: ['versionId'] },
    ],
  }, VersionRulesRow),
  versionSpecialRules: __table({
    name: 'version_special_rules',
    indexes: [
      { accessor: 'versionId', name: 'version_special_rules_version_id_idx_btree', algorithm: 'btree', columns: [
        'versionId',
      ] },
    ],
    constraints: [
      { name: 'version_special_rules_version_id_key', constraint: 'unique', columns: ['versionId'] },
    ],
  }, VersionSpecialRulesRow),
  matchHistory: __table({
    name: 'match_history',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchHistoryRow),
  matchPlayers: __table({
    name: 'match_players',
    indexes: [
    ],
    constraints: [
    ],
  }, MatchPlayersRow),
  myDecks: __table({
    name: 'my_decks',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDecksRow),
  myDraftResourceRules: __table({
    name: 'my_draft_resource_rules',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDraftResourceRulesRow),
  myDraftRules: __table({
    name: 'my_draft_rules',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDraftRulesRow),
  myDraftSpecialRules: __table({
    name: 'my_draft_special_rules',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDraftSpecialRulesRow),
  myDrafts: __table({
    name: 'my_drafts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDraftsRow),
  myMatchResourceBalances: __table({
    name: 'my_match_resource_balances',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMatchResourceBalancesRow),
  myMatches: __table({
    name: 'my_matches',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMatchesRow),
  myMemberships: __table({
    name: 'my_memberships',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMembershipsRow),
  myReactionWindows: __table({
    name: 'my_reaction_windows',
    indexes: [
    ],
    constraints: [
    ],
  }, MyReactionWindowsRow),
  roomParticipants: __table({
    name: 'room_participants',
    indexes: [
    ],
    constraints: [
    ],
  }, RoomParticipantsRow),
  visibleMatchCards: __table({
    name: 'visible_match_cards',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleMatchCardsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_coin", AddCoinReducer),
  __reducerSchema("add_dice", AddDiceReducer),
  __reducerSchema("advance_turn_phase", AdvanceTurnPhaseReducer),
  __reducerSchema("concede_match", ConcedeMatchReducer),
  __reducerSchema("create_card", CreateCardReducer),
  __reducerSchema("create_card_format", CreateCardFormatReducer),
  __reducerSchema("create_card_interaction", CreateCardInteractionReducer),
  __reducerSchema("create_card_trigger", CreateCardTriggerReducer),
  __reducerSchema("create_constraint", CreateConstraintReducer),
  __reducerSchema("create_deck_rules", CreateDeckRulesReducer),
  __reducerSchema("create_example_draft", CreateExampleDraftReducer),
  __reducerSchema("create_field", CreateFieldReducer),
  __reducerSchema("create_game_draft", CreateGameDraftReducer),
  __reducerSchema("create_hand_size", CreateHandSizeReducer),
  __reducerSchema("create_life", CreateLifeReducer),
  __reducerSchema("create_participant_limits", CreateParticipantLimitsReducer),
  __reducerSchema("create_room", CreateRoomReducer),
  __reducerSchema("create_setup", CreateSetupReducer),
  __reducerSchema("create_space", CreateSpaceReducer),
  __reducerSchema("create_starter_deck", CreateStarterDeckReducer),
  __reducerSchema("create_sub_phases", CreateSubPhasesReducer),
  __reducerSchema("create_turn_phases", CreateTurnPhasesReducer),
  __reducerSchema("create_win_condition", CreateWinConditionReducer),
  __reducerSchema("delete_deck", DeleteDeckReducer),
  __reducerSchema("delete_decks", DeleteDecksReducer),
  __reducerSchema("delete_games", DeleteGamesReducer),
  __reducerSchema("join_room", JoinRoomReducer),
  __reducerSchema("leave_room", LeaveRoomReducer),
  __reducerSchema("pass_reaction", PassReactionReducer),
  __reducerSchema("publish_game", PublishGameReducer),
  __reducerSchema("react_to_action", ReactToActionReducer),
  __reducerSchema("save_deck", SaveDeckReducer),
  __reducerSchema("select_deck", SelectDeckReducer),
  __reducerSchema("set_name", SetNameReducer),
  __reducerSchema("set_ready", SetReadyReducer),
  __reducerSchema("start_match", StartMatchReducer),
  __reducerSchema("take_action", TakeActionReducer),
  __reducerSchema("update_designer_draft", UpdateDesignerDraftReducer),
  __reducerSchema("update_game_draft", UpdateGameDraftReducer),
  __reducerSchema("update_resource_designer_draft", UpdateResourceDesignerDraftReducer),
  __reducerSchema("update_special_designer_draft", UpdateSpecialDesignerDraftReducer),
  __reducerSchema("validate_game_draft", ValidateGameDraftReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

