// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  matchId: __t.u64().name("match_id"),
  seat: __t.u8(),
  health: __t.i32(),
  resource: __t.i32(),
  eliminated: __t.bool(),
  handCount: __t.u16().name("hand_count"),
  deckCount: __t.u16().name("deck_count"),
});
