// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DeckEntry,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  versionId: __t.u64().name("version_id"),
  requestId: __t.string().name("request_id"),
  name: __t.string(),
  get entries() {
    return __t.array(DeckEntry);
  },
  revision: __t.u32(),
  complete: __t.bool(),
  updatedAt: __t.timestamp().name("updated_at"),
});
