// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameDefinition,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  requestId: __t.string().name("request_id"),
  title: __t.string(),
  description: __t.string(),
  get definition() {
    return GameDefinition;
  },
  revision: __t.u32(),
  validatedRevision: __t.option(__t.u32()).name("validated_revision"),
  validationError: __t.string().name("validation_error"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
