// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  versionId: __t.u64().name("version_id"),
  status: __t.string(),
  activeSeat: __t.u8().name("active_seat"),
  phaseIndex: __t.u16().name("phase_index"),
  subPhaseIndex: __t.u16().name("sub_phase_index"),
  turn: __t.u32(),
  revision: __t.u32(),
  winnerSeat: __t.option(__t.u8()).name("winner_seat"),
});
