// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.u64().primaryKey().name("match_id"),
  originSeat: __t.u8().name("origin_seat"),
  actionId: __t.string().name("action_id"),
  actionKind: __t.string().name("action_kind"),
  responseSeat: __t.u8().name("response_seat"),
  expiresAt: __t.timestamp().name("expires_at"),
});
