// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  host: __t.identity(),
  requestId: __t.string().name("request_id"),
  versionId: __t.u64().name("version_id"),
  name: __t.string(),
  status: __t.string(),
  playerCount: __t.u8().name("player_count"),
  matchId: __t.option(__t.u64()).name("match_id"),
  createdAt: __t.timestamp().name("created_at"),
});
