// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  DeckEntry,
} from "./types";

export default {
  deckId: __t.option(__t.u64()),
  expectedRevision: __t.option(__t.u32()),
  requestId: __t.string(),
  versionId: __t.u64(),
  name: __t.string(),
  get entries() {
    return __t.array(DeckEntry);
  },
};
