// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  SpecialRules,
  DesignerRules,
  GameDefinition,
} from "./types";

export default {
  draftId: __t.u64(),
  expectedRevision: __t.u32(),
  title: __t.string(),
  description: __t.string(),
  get definition() {
    return GameDefinition;
  },
  get rules() {
    return DesignerRules;
  },
  get special() {
    return SpecialRules;
  },
};
