// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  CardValue,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  matchId: __t.u64().name("match_id"),
  instanceId: __t.u32().name("instance_id"),
  cardId: __t.string().name("card_id"),
  ownerSeat: __t.u8().name("owner_seat"),
  zone: __t.string(),
  slotId: __t.string().name("slot_id"),
  position: __t.u32(),
  get values() {
    return __t.array(CardValue);
  },
});
